# Vector 1 dimension Matrix 2 dim vector

In [1]:
import numpy as np

a = np.array([[1,2], [3,4]])

In [2]:
a[0][0]

1

In [3]:
a[0,0]

1

In [4]:
m = np.matrix([[1,2], [3,4]])
m

matrix([[1, 2],
        [3, 4]])

In [6]:
a = np.array(m)
a

array([[1, 2],
       [3, 4]])

# Transpose

In [8]:
a.T

array([[1, 3],
       [2, 4]])

In [12]:
l = [1,2],[3,4],[5,6],[7,8],[9,0]
np.array(l).T

array([[1, 3, 5, 7, 9],
       [2, 4, 6, 8, 0]])

In [13]:
l=[1,2,3],[4,5,6],[7,8,9]
np.array(l).T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# Multiply

In [14]:
a = np.array([1,2])
b = np.array([2,1])

In [15]:
dot = 0

for x, y in zip(a,b):
    dot += x*y
    
dot

4

In [17]:
np.sum(a*b)

4

In [18]:
(a*b).sum()

4

In [19]:
np.dot(a,b)

4

In [20]:
a.dot(b)

4

# Create Array

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
np.random.random((5,5))

array([[0.08961522, 0.20339411, 0.8344299 , 0.7694021 , 0.81389132],
       [0.67505759, 0.19770189, 0.17344723, 0.27896214, 0.28696638],
       [0.91700856, 0.19393141, 0.17651691, 0.627792  , 0.26261781],
       [0.88181936, 0.09460447, 0.10789792, 0.04661127, 0.66013775],
       [0.69215511, 0.1505447 , 0.8877279 , 0.805019  , 0.31590164]])

In [25]:
np.random.randn(5,5)

array([[-0.30853991, -0.45193441,  0.75618612, -1.09851582,  0.02314387],
       [ 1.13841874,  0.06802526, -0.92054978,  0.85094098, -1.37892726],
       [-1.15256001,  1.40825856, -0.69763057,  0.07281293,  0.09223225],
       [ 0.0549465 ,  0.22860845,  0.62716544, -0.76098139,  0.71158064],
       [ 2.38860141,  1.57972998,  0.63612083, -1.42850413, -0.58988115]])

# More Matrix Operation

In [26]:
a = np.array([1,2])
a = np.array([5,6])

In [27]:
np.outer(a,b)

array([[10,  5],
       [12,  6]])

In [28]:
np.inner(a,b)

16

In [29]:
a.dot(b)

16

# Diag

In [30]:
np.diag([[1,2],[3,4]]).sum()

5

In [31]:
np.trace([[1,2],[3,4]])

5

# Coveriance

In [34]:
x = np.random.randn(10, 3)
x

array([[-0.61734964, -0.2856056 ,  2.42107012],
       [-0.90794185, -0.02042537, -0.68634695],
       [-1.26291532,  0.63716622, -0.03167517],
       [-0.12261652, -0.45328052, -0.42312141],
       [ 0.41773337,  0.8356656 ,  1.23463751],
       [ 0.61364803, -0.89878386,  1.37475073],
       [-0.49969109,  1.99094767,  0.89463157],
       [-2.00313519, -1.62161026,  0.37272842],
       [ 0.55271967,  0.0743116 , -0.35062072],
       [-0.35235632, -0.20096038,  1.26488621]])

In [36]:
cov = np.cov(x.T)
cov

array([[0.70106633, 0.18140536, 0.14282472],
       [0.18140536, 0.98207235, 0.01688146],
       [0.14282472, 0.01688146, 0.98927662]])

# Eigenvalues & Eigenvectors

In [37]:
np.linalg.eigh(cov)

(array([0.57574319, 0.96986719, 1.12680492]),
 array([[ 0.87883864,  0.02788306,  0.47630366],
        [-0.38039148,  0.64354214,  0.66419563],
        [-0.28800167, -0.76490264,  0.57617618]]))

In [38]:
np.linalg.eig(cov)

(array([0.57574319, 1.12680492, 0.96986719]),
 array([[-0.87883864,  0.47630366, -0.02788306],
        [ 0.38039148,  0.66419563, -0.64354214],
        [ 0.28800167,  0.57617618,  0.76490264]]))

# Linear System

In [45]:
a = np.array([[1,2],[3,4]])
b = np.array([3,4])

np.linalg.inv(a).dot(b)

array([-2. ,  2.5])

In [46]:
np.linalg.solve(a,b)

array([-2. ,  2.5])