In [1]:
import numpy as np

x = np.array([1,2,3,4,5])

In [2]:
print(x)
print(type(x))
x.dtype


[1 2 3 4 5]
<class 'numpy.ndarray'>


dtype('int64')

In [3]:
x.shape

(5,)

In [4]:
y = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [5]:
y.shape
# Rows, Col

(4, 3)

In [6]:
y.size

12

In [7]:
x = np.array(['hello','world'])
print(x)
print('shape: ', x.shape)
print('type: ', type(x))
print('dtype: ', x.dtype)

['hello' 'world']
shape:  (2,)
type:  <class 'numpy.ndarray'>
dtype:  <U5


In [8]:
x = np.array([1,2, 'world'])
print(x)
print('shape: ', x.shape)
print('type: ', type(x))
print('dtype: ', x.dtype) # store unicode string

['1' '2' 'world']
shape:  (3,)
type:  <class 'numpy.ndarray'>
dtype:  <U21


In [9]:
x = np.array([1,2.5,3])
print(x, x.dtype)  # Upcasting

[1.  2.5 3. ] float64


In [10]:
x = np.array([1,2.5,3], dtype=np.int64)
print(x, x.dtype)  # Upcasting

[1 2 3] int64


In [11]:
# Saving array into file
np.save('my_array', x)

In [12]:
y = np.load('my_array.npy')
print(y)

[1 2 3]
