In [1]:
import numpy as np
import time

x = np.random.random(100000)
#print(x)

start = time.time()
sum(x) / len(x)
print(time.time() - start)

0.008817672729492188


In [2]:
import numpy as np
import time

x = np.random.random(100000)
#print(x)

start = time.time()
np.mean(x)
print(time.time() - start)

0.00022864341735839844


In [3]:
import numpy as np

array = np.array([1, 4, 5, 8], float)
print(array)

[1. 4. 5. 8.]


In [4]:
if True:
    array = np.array([1, 4, 5, 8], float)
    print(array)
    print("")
    array = np.array([[1, 2, 3], [4, 5, 6]], float)  # a 2D array/Matrix
    print(array)

[1. 4. 5. 8.]

[[1. 2. 3.]
 [4. 5. 6.]]


In [5]:
if True:
    array = np.array([1, 4, 5, 8], float)
    print(array)
    print("")
    print(array[1])
    print("")
    print(array[:2])
    print("")
    array[1] = 5.0
    print(array[1])

[1. 4. 5. 8.]

4.0

[1. 4.]

5.0


In [6]:
if True:
    two_D_array = np.array([[1, 2, 3], [4, 5, 6]], float)
    print(two_D_array)
    print("")
    print(two_D_array[1][1])
    print("")
    print(two_D_array[1, :])
    print("")
    print(two_D_array[:, 2])

[[1. 2. 3.]
 [4. 5. 6.]]

5.0

[4. 5. 6.]

[3. 6.]


In [7]:
if True:
    array_1 = np.array([1, 2, 3], float)
    array_2 = np.array([5, 2, 6], float)
    print(array_1 + array_2)
    print("")
    print(array_1 - array_2)
    print("")
    print(array_1 * array_2)

[6. 4. 9.]

[-4.  0. -3.]

[ 5.  4. 18.]


In [8]:
if True:
    array_1 = np.array([[1, 2], [3, 4]], float)
    array_2 = np.array([[5, 6], [7, 8]], float)
    print(array_1 + array_2)
    print("")
    print(array_1 - array_2)
    print("")
    print(array_1 * array_2)

[[ 6.  8.]
 [10. 12.]]

[[-4. -4.]
 [-4. -4.]]

[[ 5. 12.]
 [21. 32.]]


In [9]:
'''
In addition to the standard arthimetic operations, Numpy also has a range of
other mathematical operations that you can apply to Numpy arrays, such as
mean and dot product.

Both of these functions will be useful in later programming quizzes.
'''

if True:
    array_1 = np.array([1, 2, 3], float)
    array_2 = np.array([[6], [7], [8]], float)
    print(np.mean(array_1))
    print(np.mean(array_2))
    print("")
    print(np.dot(array_1, array_2))

2.0
7.0

[44.]
